framework:
  notifier:
    chatter_transports: []
    texter_transports: []
    channel_policy:
      urgent: ['email']
      high: ['email']
      medium: ['email']
      low: ['email']
    admin_recipients:
      - { email: 'admin@example.com' }
      # Pour plusieurs admins, ajoutez une entr√©e par destinataire :
      # - { emails: 'admin2@example.com' }
      # - { emails: 'admin3@example.com' }